### ISSUE TITLE
Hajime - lack of expiration timestamp in `IZeroXSwapper.swap()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-tapioca-judging#10]
Hajime

medium

# lack of expiration timestamp in `IZeroXSwapper.swap()`

## Summary
Without a deadline parameter, the transaction may sit in the mempool and be executed at a much later time potentially resulting in a worse price for the user

## Vulnerability Detail
no expiration deadline may create a potential critical loss of funds vulnerability for any user initiating a swap
`uint256 amountOut = IZeroXSwapper(swapperTokenIn).swap(swapData.data, collateralAmount, swapData.minAmountOut);`

## Impact
lack of expiration timestamp in `IZeroXSwapper.swap()` can lead to a long transaction execution time

## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/bigBang/BBLiquidation.sol#L156-L158

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/singularity/SGLLiquidation.sol#L170-L172

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/ExampleMarketLiquidatorReceiver.sol#L80

## Tool used

Manual Review

## Recommendation
allow users to specify a deadline parameter that enforces a time limit by which the transaction must be executed.

**Comment by maarcweiss** [comment]
Invalid
