### ISSUE TITLE
duc - Unclaimed native tokens in TOFT contract can be stolen

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-tapioca-judging#107]
duc

medium

# Unclaimed native tokens in TOFT contract can be stolen

## Summary
See vulnerability detail
## Vulnerability Detail
TOFT contract has a function to rescue the stuck native tokens in contract.
```solidty=
function rescueEth(uint256 amount, address to) external onlyOwner {
    (bool success,) = to.call{value: amount}("");
    if (!success) revert TOFT_Failed();
}
```

However, the wrap function doesn't check if the `msg.value` is equal to `_amount`. Therefore, an attacker can call wrap with `msg.value` as 0 and `_amount` as the ETH balance of the contract to steal the existing native tokens in this contract.
```solidity=
function wrap(address _fromAddress, address _toAddress, uint256 _amount)
        external
        payable
        whenNotPaused
        nonReentrant
        onlyHostChain
        returns (uint256 minted)
    {
        if (erc20 == address(0)) {
            _wrapNative(_toAddress, _amount, 0);
        } ...
    }
```
```solidity=
function _wrapNative(address _toAddress, uint256 _amount, uint256 _feeAmount) internal virtual {
    vault.depositNative{value: _amount}();
    _mint(_toAddress, _amount - _feeAmount);
}
```
## Impact
Unclaimed native tokens in TOFT contract will be stolen
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/Market.sol#L419-L422
## Tool used

Manual Review

## Recommendation
Should check if `msg.value` is equal to `_amount` in the case of wrapping native tokens:
```solidity=
if (erc20 == address(0)) {
    require(msg.value == _amount);
    _wrapNative(_toAddress, _amount, 0);
}
```

**Comment by cryptotechmaker** [comment]
Low/Invalid. The contract is not supposed to hold funds (TOFTVault is responsible for that). `rescueEth` is added just in case we need to save airdropped funds
