### ISSUE TITLE
Tendency - Wrapping is Still Possible When MintCap is Zero

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-tapioca-judging#21]
Tendency

medium

# Wrapping is Still Possible When MintCap is Zero

## Summary
Wrapping/minting oft tokens is still allowed even when the mint cap is zero
## Vulnerability Detail
[mTOFT::wrap](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L287-L306) function is a functionality used for wrapping the underlying token for the contract oft token.
The supported underlying token can either be an `erc20` or a native token.

On wrap attempts, the functionality ensures the amount of minted contracts oft tokens is always below the set mint cap:
```solidity
        if (mintCap > 0) {
            if (totalSupply() + _amount > mintCap) revert mTOFT_CapNotValid();
        }

```
The problem here is that, in an emergency scenario where users have been notified to unwrap/burn their oft tokens for the underlying, and then subsequently the contract owner sets the mint cap to zero. 
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L371-L374
When the mint cap is zero, it's expected that any attempt at wrapping and thus minting the contract oft tokens should no longer be possible. The total contract oft token supply not being greater than the mint cap is an invariant that is always meant to be maintained.
As observed in the code shared above, when the mint cap is zero no reversion happens, the operation continues and subsequently oft tokens are minted to the user, breaking this invariant.

## Impact
If the contracts are currently being drained and this is the only way expected to halt further minting of oft, added with another issue I have submitted about the lack of owner setters for pausability, then users' funds will be at risk of being drained
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L296-L298
## Tool used

Manual Review

## Recommendation
consider reverting whenever the mint cap is zero
```solidity
 if (mintCap == 0) revert("zero cap");
```

Duplicate of #138

**Comment by cryptotechmaker** [comment]
Invalid
