### ISSUE TITLE
Tendency - Stuck Ether Can Easily Be Stolen

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-tapioca-judging#22]
Tendency

high

# Stuck Ether Can Easily Be Stolen

## Summary
When wrapping native tokens for oft tokens with [mTOFT::wrap](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L287-L309) function, excess sent in ether isn't refunded, this allows the use up of this stuck ether to make a free unauthorized wrap, since the functionality also doesn't ensure the correct ether amount is sent along a call.
## Vulnerability Detail
The [mTOFT::wrap](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L287-L309) function is used to unwrap the contract-supported erc20 or native token for the contract oft tokens.

When this supported token is native, users are expected to send in an ether amount equivalent to their input amount during wrap operations.
Two variants to consider during native eth wrap:
+ Ensure the sent-in ether amount exactly equals the input wrap amount
+ When the sent-in ether amount exceeds the input wrap amount, refund the excess ether to the caller.

The current wrap function doesn't do any of this, thus leaving excess sent in ether during wrap operations in the contract and thus allowing free wrap operation, since malicious users can call the wrap function with an amount and not send in any ether, as long as the contract ether balance is upto the input amount.
+ To Illustrate:

Assuming the contract currently has `1 ether` stucked, the malicious user can call [mTOFT::wrap](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L287-L309) function with `1 ether` as the input amount, the current set mint fee is `0.5%`, with an input amount of `1 ether`, the malicious user will be minted `0.995e18` oft tokens, this renders the owner-only [rescueEth](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L344-L347) functionality almost useless since the stuck ether can be used up before it's being called, or be easiky front ran.
Furthermore, the malicious user can then further unwrap the `.995e18` oft tokens for `0.995` ether

## Impact
+  theft of stuck ether
+ loss of excess sent in ether
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L287-L309
## Tool used

Manual Review

## Recommendation
When the underlying `erc20` equals `address(0)`, i.e. native wraps, add a requirement that ensures the input amount equals the sent-in `ether(msg.value)`

This should also be fixed in TOFT as well:
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/TOFT.sol#L242-L256

**Comment by cryptotechmaker** [comment]
Invalid/low. The vulnerability is represented by a user performing the action in a wrong way.
