### ISSUE TITLE
Tendency - Insufficient Solvency Checks During Borrow & Collateral Removal Actions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-tapioca-judging#25]
Tendency

high

# Insufficient Solvency Checks During Borrow & Collateral Removal Actions

## Summary
The absence of a solvency check following a borrow operation enables users to borrow significantly more than their collateral's value.
## Vulnerability Detail
When a user initiates a borrowing action using [BBBorrow::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53) function, their solvency is evaluated to determine if the borrowing operation should proceed.

+ What does it mean for a user to be solvent??

A user is said to be solvent when the value of their collateral is sufficient to cover their borrowings, considering the set collateralization ratio and the current exchange rate.

The problem with the current implementation is this, If for instance a user has `1,000 USDC` in collateral and the collateralization ratio is set at `75%`, the user should only be permitted to borrow up to `750 USDC` worth of the collateral token to remain solvent, but currently the solvency check occurs solely before the borrowing action. Assuming the user has `1,000 USDC` in collateral without any prior borrowing, the solvent check will return true, assuming the borrowed tokens are `1:1` with `USDC`, the user is meant to only be allowed to borrow up to `750` of these tokens to stay solvent, but since there is no health check after the borrow action, for `1,000 USDC` of collateral, the user can borrow an unlimited amount of tokens, so long it's below the borrow cap.

The issue also persists when a user attempts to withdraw collateral. For example, if a user has `1,000 USDC` in collateral and has borrowed up to the `75%` collateralization rate, amounting to `750 USDC` worth of borrowed tokens, invoking [BBCollateral::removeCollateral](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBCollateral.sol#L48-L56) would pass the solvency check as the user remains within the collateralization limit. However, withdrawing any collateral leaves the user significantly undercollateralized. Due to the absence of a solvency check after user collateral removal, users can literally withdraw all of their deposited collateral, effectively obtaining the borrowed tokens for free.

This same issue is present in the following contract functions:
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/singularity/SGLCollateral.sol#L48-L56

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBCollateral.sol#L48-L56

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBLeverage.sol#L53-L110

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/singularity/SGLLeverage.sol#L47-L93

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/origins/Origins.sol#L162-L169

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/origins/Origins.sol#L175-L185

## Impact
The absence of a solvency check post-borrow/collateral removal operations will leave the protocol at risk of insolvency
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53
## Tool used

Manual Review

## Recommendation
For Borrow Actions: Ensure the user's max borrowable amount is less than or equal to the input borrow amount.

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L453-L462
For Collateral Removal Actions: Add a solvency check post-collateral removal

Duplicate of #13

**Comment by cryptotechmaker** [comment]
Invalid; check the `solvent` modifier
