### ISSUE TITLE
Tendency - Flawed `_isSolvent` Check Permits Users to Borrow Without Any Prior Borrowings or Collateral, Essentially Allowing Them to Borrow Any Amount for Free.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-tapioca-judging#26]
Tendency

high

# Flawed `_isSolvent` Check Permits Users to Borrow Without Any Prior Borrowings or Collateral, Essentially Allowing Them to Borrow Any Amount for Free.

## Summary
During a borrowing action via [BBBorrow::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53) or [Origins::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/origins/Origins.sol#L175-L185), the user's solvency is verified to ensure they have deposited enough collateral to cover the borrowing. However, the solvency check fails to account for scenarios where the user has not deposited any collateral but also hasn't borrowed before. This oversight allows users without any collateral to borrow funds freely.
## Vulnerability Detail
During a borrow action, either via [BBBorrow::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53) or [Origins::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/origins/Origins.sol#L175-L185) function, the solvency of the user is checked.
The solvency check here is basically, checking to ensure the user has deposited enough collateral to cover up the borrow action.
```solidity
    modifier solvent(address from, bool liquidation) {
        updateExchangeRate();
        _accrue();

        _;

        require(_isSolvent(from, exchangeRate, liquidation), "Market: insolvent");
    }
```
The problem here is that, the [_isSolvent](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L466-L480) check assumes if the user hasn't borrowed before, i.e. the user borrow part equals zero, then the user is solvent, without considering the possibility of the user not having any deposited collateral:
```solidity
    function _isSolvent(address user, uint256 _exchangeRate, bool _liquidation) internal view returns (bool) {
        // accrue must have already been called!
        uint256 borrowPart = userBorrowPart[user];
        if (borrowPart == 0) return true; //  <--@audit
        uint256 collateralShare = userCollateralShare[user];
        if (collateralShare == 0) return false;


        Rebase memory _totalBorrow = totalBorrow;

           #######SNIP###
    }
```
+ To Illustrate

Let's assume we have a user called Bob, Bob has never borrowed or added collateral to the protocol before, but is yet said to be solvent, because Bob's current borrow amount in the protocol is zero.
Without any deposited collateral, Bob can borrow via [BBBorrow::borrow](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53)  function with any borrow amount, as long as it is below the set borrow cap.

## Impact
With users being able to borrow for free, this increases the risk of insolvency for the protocol
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/bigBang/BBBorrow.sol#L37-L53

https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/origins/Origins.sol#L175-L185
## Tool used

Manual Review

## Recommendation
Check the user collateral share before their borrow part, update [_isSolvent](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L466-L480) function to:
```solidity
    function _isSolvent(address user, uint256 _exchangeRate, bool _liquidation) internal view returns (bool) {
        // accrue must have already been called!
        uint256 collateralShare = userCollateralShare[user];
        if (collateralShare == 0) return false;
        
        uint256 borrowPart = userBorrowPart[user];
        if (borrowPart == 0) return true;



        Rebase memory _totalBorrow = totalBorrow;


        uint256 collateralAmount = yieldBox.toAmount(collateralId, collateralShare, false);
        return collateralAmount * (EXCHANGE_RATE_PRECISION / FEE_PRECISION)
            * (_liquidation ? liquidationCollateralizationRate : collateralizationRate)
        // Moved exchangeRate here instead of dividing the other side to preserve more precision
        >= (borrowPart * _totalBorrow.elastic * _exchangeRate) / _totalBorrow.base;
    }
```

Duplicate of #13

**Comment by cryptotechmaker** [comment]
Invalid; check `solvent` modifier. It checks at the end of the method when the user already has something borrowed
