### ISSUE TITLE
AuditorPraise - Fees accumulated in `singularity`  that is stored on penrose's account may be stuck in certain scenarios

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-tapioca-judging#28]
AuditorPraise

medium

# Fees accumulated in `singularity`  that is stored on penrose's account may be stuck in certain scenarios

## Summary
whenever `_totalAsset.base -=balanceOf[address(penrose)]` is < 1000 there will be a revert MinLimit(), but this can be avoided.
## Vulnerability Detail
when borrows are done `feeFraction` from borrow Amount is stored on penrose's account balance
```solidity
if (feeAmount > 0) {
            uint256 feeFraction = (feeAmount * _totalAsset.base) / fullAssetAmountBefore;
            _totalAsset.base += feeFraction.toUint128();
            balanceOf[address(penrose)] += feeFraction; //@audit
        }
```

whenever owner `refreshPenroseFees()` the `accrueInfo.feesEarnedFraction` is saved on penrose's account balance
```solidity
 // withdraw the fees accumulated in `accrueInfo.feesEarnedFraction` to the balance of `feeTo`.
        if (accrueInfo.feesEarnedFraction > 0) {
            _accrue();
            uint256 _feesEarnedFraction = accrueInfo.feesEarnedFraction;
            balanceOf[_feeTo] += _feesEarnedFraction;// @audit
            emit Transfer(address(0), _feeTo, _feesEarnedFraction);
            accrueInfo.feesEarnedFraction = 0;
            emit LogWithdrawFees(_feeTo, _feesEarnedFraction);
        }
```

There's a possibility that  `_totalAsset.base -=balanceOf[address(penrose)]` could be < 1000 and there will be a revert MinLimit() and owner won't be able to withdraw the accumulated fees, but this can be avoided.

This can be avoided in `SGLCommon._removeAsset()` by checking if `_totalAsset.base -= fraction.toUint128() ` is < 1000, and if it is, 1000 should be subtracted from fraction instead of reverting. 
```solidity
    _totalAsset.base -= fraction.toUint128();
        if (_totalAsset.base < 1000) revert MinLimit();
```

i believe this will be better than reverting the tx's with `revert MinLimit()`
## Impact
Fees accumulated in `singularity`  that is stored in penrose's account may be stuck in certain scenarios, especially when _totalAsset.base -=balanceOf[address(penrose)] is < 1000

please consider that fees accumulated in `singularity`  is likely to grow rapidly and constantly considering the number of users that will be borrowing and `accrueInfo.feesEarnedFraction`. So _totalAsset.base -=balanceOf[address(penrose)] being < 1000, will probably make the accumulated fees to be stuck and there's no other way to reduce balanceOf[address(penrose)] therefore the balance will just keep accumulating and increasing
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/singularity/SGLCommon.sol#L207-L208
## Tool used

Manual Review

## Recommendation
In `SGLCommon._removeAsset()`, if `_totalAsset.base -= fraction.toUint128() ` is < 1000, 1000 should be subtracted from fraction instead of reverting with `revert MinLimit()`

**Comment by cryptotechmaker** [comment]
Invalid/Low; A fee <1000 can be considered 0 anyway. That's a number <1000 for a token with 18 decimals
