### ISSUE TITLE
Tendency - Unfair Liquidation Risk Due to Unvalidated Exchange Rate

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-tapioca-judging#30]
Tendency

medium

# Unfair Liquidation Risk Due to Unvalidated Exchange Rate

## Summary
During liquidation events, the protocol relies on the [_updateOracleRateForLiquidations](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L427-L439) function to refresh exchange rates for accurate computations. However, this function fails to properly validate the exchange rate, potentially leading to unfair liquidations.

## Vulnerability Detail
During a liquidation, [_updateOracleRateForLiquidations](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L427-L439) is invoked to update the exchange rate to the latest rate, the updated exchange rate is then used for computations during the liquidation logic.

The problem here is that, [_updateOracleRateForLiquidations](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L427-L439) function doesn't ensure that the stored exchange rate is still a valid rate, when the Oracle wasn't updated `(i.e _updated = false)`:
```solidity
    function _updateOracleRateForLiquidations() internal {
        try oracle.get(oracleData) returns (bool _updated, uint256 _exchangeRate) {
            if (_updated && _exchangeRate > 0) {
                exchangeRate = _exchangeRate; //update cached rate
                rateTimestamp = block.timestamp;
            } else {
                _exchangeRate = exchangeRate; //use stored rate
                if (_exchangeRate == 0) revert ExchangeRateNotValid();
            }
        } catch {
            if (exchangeRate == 0) revert ExchangeRateNotValid();
        }
    }
```
And according to the protocol an exchange rate is only considered to be valid when 
`rateTimestamp + rateValidDuration >= block.timestamp,`, where the `rateValidDuration` is currently set to `24 hours`, so if the exchange rate hasn't been updated for longer than `24 hours`, the stored rate is considered to be an invalid rate.

## Impact
The use of outdated exchange rates could cause unfair liquidations, since a user could appear to be liquidatable when they aren't with the current rate.
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L427-L439
## Tool used

Manual Review

## Recommendation
Use [updateExchangeRate](https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/Market.sol#L372-L385) function instead, to ensure the stored exchange rate will be a valid rate.

**Comment by cryptotechmaker** [comment]
Invalid; liquidation has to be performed even if the rate is not updated

**Comment by dmitriia** [comment]
Escalate
Both 11 and 30 are not valid: liquidation not requiring live rate is a feature introduced as a [C4-1026](https://github.com/code-423n4/2023-07-tapioca-findings/issues/1026) mitigation in [PR 324](https://github.com/Tapioca-DAO/Tapioca-bar/pull/324), not a bug.
Also, 11 and 30 are dups between themselves, aren't dups to 79 (which is about handling exchange rate on risk increasing operations, not for liquidation).

**Comment by sherlock-admin2** [comment]
> Escalate
> Both 11 and 30 are not valid: liquidation not requiring live rate is a feature introduced as a [C4-1026](https://github.com/code-423n4/2023-07-tapioca-findings/issues/1026) mitigation in [PR 324](https://github.com/Tapioca-DAO/Tapioca-bar/pull/324), not a bug.
> Also, 11 and 30 are dups between themselves, aren't dups to 79 (which is about handling exchange rate on risk increasing operations, not for liquidation).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@dmitriia Agree to your comments in #11

**Comment by cvetanovv** [comment]
I agree with the escalation of @dmitriia #11 and #30 being invalidated.

**Comment by cvetanovv** [comment]
Planning to accept the escalation and invalidate the issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dmitriia](https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/30/#issuecomment-2032267432): accepted
