### ISSUE TITLE
cergyk - Origins.sol no function to add allowedParticipants

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-tapioca-judging#38]
cergyk

medium

# Origins.sol no function to add allowedParticipants

## Summary
Some functions in Origins.sol are only for allowed participants, but no function is implemented to enable adding or removing allowed participants.

This means these functions are restricted to only being the owner of the contract.

## Vulnerability Detail

We can see that the owner is added to the mapping `allowedParticipants`, but no other address can ever be added:
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/origins/Origins.sol#L74

## Impact
The functionality of the contract is restricted, since only owner can participate in it

## Tool used

Manual Review

## Recommendation
Add a `addAllowed` function

**Comment by cryptotechmaker** [comment]
Low; The only participant in Origins.sol is us.
The auditor is right considering the code, but wrong in terms of the context. We can add a method for that just in case.
