### ISSUE TITLE
cergyk - TOFTMarketReceiverModule::leverageUpReceiver Incorrect approval handling

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-tapioca-judging#47]
cergyk

medium

# TOFTMarketReceiverModule::leverageUpReceiver Incorrect approval handling

## Summary
leverageUpReceiver grants approval to the market on behalf of `msg.sender` before calling `IMarket::buyCollateral`. However buyCollateral expects to be approved on YieldBox shares and not TOFT directly, so the call should revert.

## Vulnerability Detail
In `TOFTMarketReceiverModule::leverageUpReceiver` TOFT is approved directly to the market:
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/TapiocaZ/contracts/tOFT/modules/TOFTMarketReceiverModule.sol#L89

However in BBLeverage/SGLLeverage:
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/singularity/SGLLeverage.sol#L71

Yieldbox allowance is expected in order to withdraw to current market, and not TOFT (underlying) approval. 

## Impact
The receiver module will always revert when using `leverageUpReceiver` compose message type 

## Tool used

Manual Review

## Recommendation
Deposit the current TOFT to YieldBox and approve that, instead of approving TOFT directly in `TOFTMarketReceiverModule::leverageUpReceiver`

Duplicate of #100

**Comment by cryptocoderkkk** [comment]
This doesn't look like a duplicate of #100  @nevillehuang 

I think this issue is about a fix like this: https://github.com/Tapioca-DAO/TapiocaZ/pull/194
