### ISSUE TITLE
GiuseppeDeLaZara - Pausable is not implemented

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-tapioca-judging#66]
GiuseppeDeLaZara

medium

# Pausable is not implemented

## Summary

Several contracts in the Tapioca protocol are extending the `Pausable` contract but are not implementing the pausing/unpausing functionality. This means that critical functions cannot be paused in case of emergency.

## Vulnerability Detail

`mTOFT.sol`, `TOFT.sol`, `Usdo.sol`, `AssetToSGLPLeverageExecutor.sol` contracts are extending the `Pausable` contract but are not implementing the pausing/unpausing functionality.

```solidity
## Pausable.sol

function _pause() internal virtual whenNotPaused {
    _paused = true;
    emit Paused(_msgSender());
}

function _unpause() internal virtual whenPaused {
    _paused = false;
    emit Unpaused(_msgSender());
}
```

There are numerous functions in the aforementioned contracts that use the `whenNotPaused` modifier, e.g.

```solidity
## TOFT.sol

function executeModule(ITOFT.Module _module, bytes memory _data, bool _forwardRevert)
    external
    payable
    whenNotPaused
    returns (bytes memory returnData)
{
    return _executeModule(uint8(_module), _data, _forwardRevert);
}
```

But pausing can never be activated as the pausing functionality is not implemented.

## Impact

Critical functions cannot be paused in case of emergency as the pausing functionality is not implemented.

## Code Snippet

- https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/mTOFT.sol#L50
- https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/TapiocaZ/contracts/tOFT/TOFT.sol#L47
- https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/usdo/Usdo.sol#L45
- https://github.com/sherlock-audit/2024-02-tapioca/blob/dc2464f420927409a67763de6ec60fe5c028ab0e/Tapioca-bar/contracts/markets/leverage/AssetToSGLPLeverageExecutor.sol#L40

## Tool used

Manual Review

## Recommendation
Include the following function in the contracts to implement the pausing functionality:

```solidity
function pause(bool pause) external onlyOwner {
    pause ? _pause() : _unpause();
}
```

Duplicate of #64

**Comment by maarcweiss** [comment]
Dup of https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/64
