### ISSUE TITLE
Hajime - unchecked loop increments no valid in solidity v0.8.22

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-tapioca-judging#9]
Hajime

medium

# unchecked loop increments no valid in solidity v0.8.22

## Summary

The new optimization in v0.8.22 removes the need for poor unchecked increment patterns in for loop bodies such

## Vulnerability Detail
Unnecessary unchecked optimizition in Solidity v0.8.22

## Impact
Solidity 0.8.22 introduces an overflow check optimization that automatically generates an unchecked arithmetic increment of the counter of for loops.

## Code Snippet

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/bigBang/BBLiquidation.sol#L314

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/singularity/SGLLiquidation.sol#L383-L385

## Tool used

Manual Review

## Recommendation
do not use `unchecked`

**Comment by maarcweiss** [comment]
Invalid
